# Generated by Django 5.2.1 on 2025-05-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('TD', 'todo'), ('IP', 'in-progress'), ('DN', 'done')], default='TD', max_length=2),
        ),
    ]
